spring:
  application:
    name: find-your-home
  datasource:
    url: "jdbc:postgresql://localhost:5432/find_your_home_db"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#max file and request size
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB